version: '3'
services:
  mongodb:
    build:
      dockerfile: Dockerfile.dev
      context: ./mongodb
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:      
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=reading-monk-db
      - MONGODB_USER=mongodb
      - MONGODB_DATABASE=reading-monk-db
      - MONGODB_PASS=mongodb
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=reading-monk-db
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGODB_USER=mongodb
      - MONGODB_DATABASE=reading-monk-db
      - MONGODB_PASS=mongodb
      - TOKEN_SECRET=secret_for_jwt
      - MAILGUN_API_KEY=b41f34fb6db4435bc82f59e8eafa62fc-d32d817f-a3c12753 
      - MAILGUN_DOMAIN=sandboxaa83f7dd451f4e09b457a736dbadbc73.mailgun.org     
    depends_on:
      - mongodb         
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api